[tox]
envlist = py39, py310, py311, py312
skip_missing_interpreters = True
minversion = 3.4.0

[testenv]
commands     = pytest --junit-xml test-reports/pyunit.xml --cov --cov-branch --cov-report term --cov-report html:test-reports/htmlcov --cov-report xml:test-reports/coverage.xml {posargs:test}

setenv =
    PYTHONUNBUFFERED = yes
    PYTHONHASHSEED   = 3104489401

deps =
    pytest
    pytest-mock
    pytest-cov
    coverage
    numpy
    pandas
    PyYAML
    # torch is optional — tests that need it are skipped if not installed
    ../pegasus-api
